Fix kafo master support matrix
theforeman/foreman-infra pull request #1476
Opened 2020-10-26 16:59 UTC by ehelms

2020-10-26 18:19 UTC, ekohl reviewed
We should also codify this in the kafo gemspec with a minimal required Ruby version. It would mean a major new version, of the gem but I think that's fair at this point. Then we can also remove all the RUBY_VERSION conditionals.

2020-10-28 12:00 UTC, ehelms commented
I am changing the tactic with this PR to just drop the test of the master branch of kafo and kafo_parsers. Given they do not see a lot of change, and that we do not have nightly releases of Kafo I think it's OK to reduce the number of jobs to PR jobs and let release PRs indicate the status when doing a release.

2020-11-13 12:15 UTC, ekohl requested changes

2020-11-13 12:15 UTC, ekohl commented on puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_parsers_master.yml
> -      - shell: !include-raw: scripts/test/test_kafo_parsers_master.sh
This file is now unused.

2020-11-13 12:15 UTC, ekohl commented on puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_master.yaml
> -      - test_kafo
This builder is now unused

2020-11-13 13:11 UTC, ekohl approved these changes

2020-11-13 13:12 UTC, merged