Add ci.theforeman.org jobs to the update jobs job
theforeman/foreman-infra pull request #1478
Opened 2020-10-29 00:16 UTC by ehelms

The credentials will need to be created and added if the structure is agreed upon. After this PR, we can then:

 * move the creation of this job to the puppet module
 * move the bulk of the JJB configurations to a top level directory

2020-12-16 07:34 UTC, evgeni requested changes
Another thing that I wonder about the following:

You added `--delete-old` here, but we also have https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/unmanaged_jobs.rb that is run via cron 
https://github.com/theforeman/foreman-infra/blob/3d24ecf3695dec14a68458467e075fe651d63b89/puppet/modules/jenkins_job_builder/manifests/config.pp#L40-L46

and then we have another cron that runs `update --delete-old`:
https://github.com/theforeman/foreman-infra/blob/3d24ecf3695dec14a68458467e075fe651d63b89/puppet/modules/jenkins_job_builder/manifests/config.pp#L25-L31

and finally we have the old deployment that has no `--delete-old` and gets triggered by puppet whenever stuff changes:
https://github.com/theforeman/foreman-infra/blob/3d24ecf3695dec14a68458467e075fe651d63b89/puppet/modules/jenkins_job_builder/manifests/config.pp#L40-L46

My understanding is that your plan is to have Puppet only deploy the `foreman-infra-jenkins-jobs-update` job (by calling `jjb update foreman-infra-jenkins-jobs-update` or similar) and then let Jenkins do the rest.

Now my questions:
* Should `foreman-infra-jenkins-jobs-update` get a timed trigger and thus replace the cron job too?
* Do we really need the `unmanaged_jobs.rb` thing? Doesn't `--delete-old` take care of that?

2020-12-16 07:34 UTC, evgeni commented on puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/infra/updateJobs.groovy
> +                    virtEnv('jjb-venv', "cd ./ci/theforeman.org && jenkins-jobs --conf ./foreman_jenkins.ini --user ${env.USERNAME} --password '${env.PASSWORD}' update --delete-old -r ./jobs")
```suggestion
                    virtEnv('jjb-venv', "cd ./ci/theforeman.org && jenkins-jobs --conf ./foreman_jenkins.ini --user ${env.USERNAME} --password '${env.PASSWORD}' update --delete-old -r .")
```

the directory layout is not 100% identical between the tfm and the centos jenkins

2020-12-16 15:13 UTC, ehelms commented
I was thinking of a prepare and use the new for a while and then remove the old strategy. 

> Should foreman-infra-jenkins-jobs-update get a timed trigger and thus replace the cron job too?

For handling the periodic removal of jobs that are not tracked in git rather than relying on merges to this repository to go find them? That probably makes sense when we replace the cron job. I'd like to do that in two separate steps unless there is a good reason not to.

2021-01-05 07:33 UTC, evgeni requested changes
the comment about the folder structure (https://github.com/theforeman/foreman-infra/pull/1478/files#r544066487) still stands and needs addressing

2021-01-05 07:34 UTC, evgeni commented
> For handling the periodic removal of jobs that are not tracked in git rather than relying on merges to this repository to go find them? That probably makes sense when we replace the cron job. I'd like to do that in two separate steps unless there is a good reason not to.

Absolutely, was just curious if you have a "roadmap" besides this PR :)

2021-01-08 11:36 UTC, evgeni approved these changes

2021-01-08 11:36 UTC, merged