Make F60addforemanrepo a static hook & include GPG
theforeman/foreman-infra pull request #1650
Opened 2021-09-02 13:24 UTC by ekohl

This rewrites to hook to a pure bash file without any ERB templating. The $DISTRIBUTION variable is guaranteed to be available by pbuilder. It also uses heredoc for a more readable script. The hook already sets up the Foreman repositories, having the GPG setup in the same place keeps it local.

2021-09-02 13:26 UTC, evgeni commented on puppet/modules/slave/files/pbuilder_F60addforemanrepo
> +	mQINBGD6Y/UBEADOhGOD74lvHdUAew1cHjAUTbopfoXvFvo5jXs4ra3IblnzPEOJ
you lost a newline between the "begin block" and the actual content, and I know from painful experience, that `apt` doesn't like that (gpg does)

2021-09-02 13:28 UTC, evgeni commented
```
jenkins@deb-node01:~$ FOREMAN_VERSION=nightly sudo pbuilder-buster64 login
…
root@deb-node01:/# echo $DISTRIBUTION
<empty>
```

2021-09-02 13:30 UTC, ekohl commented
From `man pbuilder`:
```
       --hookdir [location of user scripts]

              [...]

              In your hook the following environment variables are available:
               PBUILDER_OPERATION a string indicating which of the pbuilder command has been called.  Possible values are build, clean, create, debuild, dumpconfig, execute, lo‐
               gin, update.
               BUILDDIR the place where the build happens, the sources are inside a directory named <package>-<version>.
               DISTRIBUTION the name of the used distribution, as provided by the DISTRIBUTION config value, or the --distribution command line flag.
               BUILD_ARCH contains the build architecture, the architecture the package is building on.
               HOST_ARCH contains the host architecture, the architecture the package is building for.
```

I trusted this.

2021-09-02 13:33 UTC, evgeni commented
Hmm, it's only available in the hooks? maybe.

2021-09-02 13:38 UTC, evgeni commented
Tried, available in hooks, thanks

2021-09-02 13:40 UTC, evgeni requested changes

2021-09-02 13:40 UTC, evgeni commented on puppet/modules/slave/files/pbuilder_F60addforemanrepo
> +	cat > /etc/apt/trusted.gpg.d/foreman.gpg <<-EOF
```suggestion
	cat > /etc/apt/trusted.gpg.d/foreman.asc <<-EOF
```

2021-09-02 13:40 UTC, ekohl commented on puppet/modules/slave/files/pbuilder_F60addforemanrepo
> +	cat > /etc/apt/trusted.gpg.d/foreman.gpg <<-EOF
Bleh, rebases gone wrong.

2021-09-02 14:10 UTC, ekohl commented
https://github.com/theforeman/foreman-infra/pull/1646 includes this. I'd also be happy if you merge that instead :)

2021-09-21 13:25 UTC, evgeni approved these changes

2021-09-21 13:25 UTC, merged